# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Thoams Anders
title: Technical Architect
email: thomas.ta.anders@outlook.de
website: tndrs.github.io | tndrs.cc

# Social links
twitter_username: tndrs089
github_username:  tndrs
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: tndrs089
#linkedin_username: jameswgrant
# pinterest_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
Blablabla
Also Bla
  I want to help customers with: <mark>AWS</mark> and <mark>DevOps</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
